### ISSUE TITLE
Failing installation

### ISSUE THREAD

**Issue by rashthedude** [jcreigno/nodejs-mail-notifier#22]
Setting the version to "0.2.5" in package.json and running npm install throws an error: "No compatible version found: mail-notifier@0.2.5". I'm currently using Node version 0.10.26 and npm version 3.5.1. Could you maybe give me a heads up?

**Comment by jcreigno** [comment]
I've published the 0.2.5 version to npm. You can now install it.

**Comment by rashthedude** [comment]
Hi @jcreigno it seems as though you haven't pushed version 0.2.6 to npm as of yet?

**Comment by rashthedude** [comment]
Ah I can see 0.3.0 so never mind :-)
