### ISSUE TITLE
Event for when mail-notifier connects to IMAP

### ISSUE THREAD

**Issue by KrisSiegel** [jcreigno/nodejs-mail-notifier#23]
I'm looking to be able to trigger a message when successful connection to the IMAP server occurs. This is something the outdated mail-listener2 module provided. Is there anyway to get this out of the existing implementation? If not, any plans to add this? I can take a look at creating a PR I just don't have time to dig through the code at the moment.

Thanks!

**Comment by jcreigno** [comment]
I've added a `connected` event that is fired when the connection is established with the imap server in 7d1021696c267bfe484102efcb283bdc4a2fc8c2 .

**Comment by KrisSiegel** [comment]
Fantastic! Thanks! A++. Would post issue again :)

Are you going to publish a new version to npm for this modification?

**Comment by jcreigno** [comment]
Not sure I like issues that much :) , but requests for improvement are welcome.

I've published version 0.3.0 to npm.

**Comment by KrisSiegel** [comment]
I saw. Thanks!
