### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by ybrodsky** [jcreigno/nodejs-mail-notifier#24]
Is there any way to set a timeout?
Also, I want to disconnect after checking for mails (if there's mail, after getting them, if there's not after checking). Is there any option to do this?

Thanks.

**Comment by bcompagnat** [comment]
`var notifier = require('mail-notifier');

var imap = { // your configs ...
                       connTimeout : 20000, // Time out for connection
			authTimeout : 20000 // Time out for authentication
            }
notifier = notifier(imap)`

**Comment by ybrodsky** [comment]
Thanks
