### ISSUE TITLE
Imap close doesnt trigger end or error event.

### ISSUE THREAD

**Issue by alpha14** [jcreigno/nodejs-mail-notifier#27]
The connection stops without being caught either by "end" or "error" events.

Debug log: 

> mailnotifier no new mail in INBOX +0ms
>   imap => 'IDLE IDLE' +0ms
>   imap <= '+ idling' +71ms
>   imap [connection] Closed +30s
>   mailnotifier imap close : errored +1ms

Maybe add 
`self.emit('end');`
in self.imap.once('close') ?

**Comment by Royalgamer06** [comment]
This
