### ISSUE TITLE
Unable to get the list of sent mails

### ISSUE THREAD

**Issue by b3rew** [jcreigno/nodejs-mail-notifier#36]
I was trying to get the list of sent emails by changing  `box` option  to `[Gmail]/Sent Mail`, but i didn't get any response,
on the other hand `INBOX` works fine

if u have any suggestions or corrections, i need your help
thanks

**Comment by b3rew** [comment]
it could be because it is using `'UNSEEN'` as its default search option but if i change the default it works fine for example 

```
search: [['TO', 'email@gmail.com']]
```

what can i change the search option to, to get all sent mails?

**Comment by jcreigno** [comment]
Hi @b3rew 

Set `search` to SEEN. 
CF https://tools.ietf.org/search/rfc3501#section-6.4.4
