### ISSUE TITLE
self is not defined on stop()

### ISSUE THREAD

**Issue by b3rew** [jcreigno/nodejs-mail-notifier#37]
I am getting `ReferenceError: self is not defined` error when i use stop()

EDIT:
i think because the npm package is not updated, the github & the npm version is different

https://github.com/jcreigno/nodejs-mail-notifier/blob/master/index.js#L106 in not included on the npm version

please update npm and close this issue
thanks

**Comment by jcreigno** [comment]
I've just published  tag 0.4.1 to npm.

Thanks
