### ISSUE TITLE
mime.extension is not a function

### ISSUE THREAD

**Issue by lacivert** [jcreigno/nodejs-mail-notifier#43]
EDIT: There is nothing to do with the code block below (with `if(mail.attachments)`, it has problem without it as well)

I basically try the code on  #16 

```
notifier(imap)
  .on('mail', mail => {
    console.log(mail);
    if(mail.attachments) {
        mail.attachments.forEach(function(attachment){
          console.log('attachment.generatedFileName',attachment.generatedFileName)
            var bufferStream = new stream.Transform();
            bufferStream.push(attachment.content);
            var output = fs.createWriteStream('/tmp/' + attachment.generatedFileName);
            bufferStream.pipe(output);
        });
    }
  })
  .start();
```

I try an email with a basic image attachment and I got this error:

```
/Users/yasin/dev/maildeneme/node_modules/mail-notifier/node_modules/mailparser/lib/mailparser.js:1407
        defaultExt = mime.extension(contentType);
                          ^

TypeError: mime.extension is not a function
    at MailParser._generateFileName (/Users/yasin/dev/maildeneme/node_modules/mail-notifier/node_modules/mailparser/lib/mailparser.js:1407:27)
    at MailParser._processStateHeader (/Users/yasin/dev/maildeneme/node_modules/mail-notifier/node_modules/mailparser/lib/mailparser.js:309:61)
    at MailParser._process (/Users/yasin/dev/maildeneme/node_modules/mail-notifier/node_modules/mailparser/lib/mailparser.js:227:22)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by jcreigno** [comment]
Its working fine for me. However, I'm able to reproduce this issue if I clear my `node_modules` directory.

It seems that npm is pulling mime@2.0.3 now. This is due to the incorrect version specification in `mailparser` which states '*'.

**Comment by lacivert** [comment]
I got the code of index.js and changed some. You can also use simpleParser to make things easier for the returning `mail` object. It may also be an option?

**Comment by jcreigno** [comment]
I've upgraded mailparser to 0.6.2 which uses a correct version spec for mime. I might need to upgrade to version 2.x.x of mail parser later.

**Comment by PavelValentov** [comment]
I've changed the call
`defaultExt = mime.extension(contentType);`
to
`defaultExt = mime.getExtension(contentType);`

It works.

**Comment by AtypicalSysAdmin** [comment]
> I've changed the call `defaultExt = mime.extension(contentType);` to `defaultExt = mime.getExtension(contentType);`
> 
> It works.

Cheers
