### ISSUE TITLE
TypeError: mime.extension is not a function (Since previous close of issue)

### ISSUE THREAD

**Issue by Alxandir** [jcreigno/nodejs-mail-notifier#44]
I am running this node module at version "^0.4.1", and I am getting the "Type Error: mime.extension is not a function" issue on some emails. I have reinstalled the dependancy since the fix for Issue #43 was applied, but I am able to reliably recreate the issue when I receive a calendar update/invite from Google Calendar, due to the formatting of their emails.
Any help on this would be greatly appreciated!

**Comment by hevilp** [comment]
I got the error too

**Comment by popere** [comment]
Me too, maybe an other lower version works :S

**Comment by jcreigno** [comment]
Hi !
Have you tried to install the current master ? It should be fixed.
Just let me know if it work for you and l'll publish the version (5.0.0) to

**Comment by snics** [comment]
Hi @jcreigno 

Your changes fixed the bug with me. Thank you very much!

**Comment by jcreigno** [comment]
Thanks @snics for your feedback.
I've pushed the 0.5.0 release.

**Comment by ziyaullah** [comment]
Am getting this error "Type Error: mime.extension is not a function", @jcreigno , how to install current master. can you please tell installation steps. Sorry if it is a basic question because i am new to this. Thanks in advance
