### ISSUE TITLE
After sometime mail-notifier is not checking emails

### ISSUE THREAD

**Issue by jarbaspsf** [jcreigno/nodejs-mail-notifier#5]
In five or ten minutes after run the script mail-notifier does not check any new emails

**Comment by Shrutichhatbar** [comment]
Is it resolved?

**Comment by Shrutichhatbar** [comment]
I am using mail-listenter2 and facing problems so was thinking to switch to mail notifier?

**Comment by ZuzooVn** [comment]
@Shrutichhatbar : Did you find the solution?

**Comment by jcreigno** [comment]
It's not a bug, the server is closing the connection 

```
imap <= '* BYE Session expired, please login again.'
```
You need to restart when you get a `end` event 

```js
var n = notifier(imap);
n.on('end', function () { // session closed
  n.start();
}).on('mail',function(m){
    console.log(m.from[0].address, m.subject);
}).start();

```

**Comment by bcompagnat** [comment]
This helped me a lot, can you please put more information on the documentation about this because its not intuitive to use .on('end') with the actual doc.

**Comment by KrisSiegel** [comment]
Just ran across this issue and @jcreigno's comment was very helpful. :+1:

**Comment by jcreigno** [comment]
I've added the code sample to the readme to explain how to restart after an `end` event.
