### ISSUE TITLE
markSeen False = duplicate emails

### ISSUE THREAD

**Issue by jim-alexander** [jcreigno/nodejs-mail-notifier#64]
If markSeen is equal to false and i have 5 unread emails and a new email comes in, it triggers the on mail function 6 times, 5 for the existing unread emails and once for the new email.

Is this a feature or a bug... bug for my use case anyway

**Comment by jim-alexander** [comment]
Turns out its a feature, 
If the app isn't running and you accrue emails; when you turn the app back on, it will do the function to all those emails...
The more you know

**Comment by giacomobartoli** [comment]
@jim-alexander so.. how did you fix it? I am experiencing the same issue

**Comment by jim-alexander** [comment]
markSeen has to be set as true @giacomobartoli

**Comment by giacomobartoli** [comment]
Thank you @jim-alexander
